# Generated by Django 5.2.9 on 2025-12-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='Username'),
        ),
    ]
